const constants = {
    //FETCH_HEALTH_RECORD: "FETCH_HEALTH_RECORD",
    //FETCH_DEMOGRAPHICS: "FETCH_DEMOGRAPHICS",
    //FETCH_ALLERGIES: "FETCH_ALLERGIES",
    API_STARTS: "API_STARTS",
    API_END: "API_END",
    SET_DEMOGRAPHIC_DETAILS: "SET_DEMOGRAPHIC_DETAILS",
    SET_ALLERGY_DETAILS: "SET_ALLERGY_DETAILS",
    SET_MEDICATION_DETAILS: "SET_MEDICATION_DETAILS",
    SET_PROVIDER_DETAILS: "SET_PROVIDER_DETAILS"
}

export default constants;